### ISSUE TITLE
Office documents open in read only mode

### ISSUE THREAD

**Issue by MeliSantana** [FubarDevelopment/WebDavServer#18]
Hi!
I'm using the fubar webdav server, with a Custom FIle System but using the InMemoryLock. It works perfectly with all the files except for office. It opens in read only mode, I have checked the headers to make sure the lock is returned in the Options request and Dav 2 header is present in all responses too. Is an known issue or it is something that can be solved somehow?

Thank you for the help you could provide

**Comment by fubar-coder** [comment]
Sorry, I don't know why Office opens the file in r/o mode 😞

**Comment by MeliSantana** [comment]
Hi, I continued researching a bit about the issue. There is a header missing in the response. MS-Author-Via.
If you add that header in the Options response, it is fixed. 
Regards

**Comment by fubar-coder** [comment]
I'd suggest that you implement it as a custom (dead?) property. You have several choices:

- Implement it in `IWebDavClass1.GetProperties` with redirect to the standard implementation `WebDavDispatcherClass1`
- Set the `MS-Author-Via` as dead property for all office documents once
- Set the `MS-Author-Via` as dead property for all office documents when the file system gets mounted

**Comment by ViceIce** [comment]
I solved this by adding custom middleware.

```csharp
app.Use(async (context, nextMiddleware) =>
{
  context.Response.OnStarting(() =>
  {
    if (context.Request.Method.Equals("OPTIONS"))
      context.Response.Headers.Add("MS-Author-Via", "DAV");
    return Task.FromResult(0);
  });
  await nextMiddleware();
});
```
