### ISSUE TITLE
Documents in an SQLServer Database Table 

### ISSUE THREAD

**Issue by madrianr** [FubarDevelopment/WebDavServer#19]
We are saving all our documents in an SQLServer Database Table - in our current app, which is a client application we can use office api to open and edit office documents.
 
Now we are migrating the client to a ASP.NET MVC Core Webapplication and need also to open and edit Word/Excel documents from the browser.
 
Is it possible with WebDAVServer to open/stream Word/Excel documents directly from the database and then also save them back to the database (we Need no filesystem and Folders only open the doc from the DB and save them back)?

robert

**Comment by fubar-coder** [comment]
You have to develop your own virtual file system. You can take the `FubarDev.WebDavServer.FileSystem.SQLite` project as a starting point.

**Comment by madrianr** [comment]
I have looked into you solution and it seems to be not a trivial task to di this - because I didn't need all the complex structurs only to read a stream from the DB, open Word, Excel and save that stream back to the DB - no filesystem structure etc.

Is it possible to integrate the WebDav Server into an existing ASP.NET Core APP and have specific Path there or is it necessary to have a seperate Web for that?

robert

**Comment by fubar-coder** [comment]
This project uses ASP.NET Core 1.1 and is AFAIK not compatible with 2.0. IOW: You can integrate it in a ASP.NET Core 1.1 project (but not 2.0+). The virtual file system stuff with collections and documents is required by the WebDAV RFC. You might get away by simply implementing the functionality for a root collection and its documents and throw a "NotImplementedException" for everything else.

**Comment by fubar-coder** [comment]
You can now use the server in ASP.NET Core 2.0, but I don't have plans to create an SQL Server backend. You're welcome to create a PR for this feature, but the WebDAV server itself is complete (as specified by the RFCs for Class 1 and 2).
