### ISSUE TITLE
ContentType

### ISSUE THREAD

**Issue by ViceIce** [FubarDevelopment/WebDavServer#22]
Hi,

how ca i set /get the correct content type for the files. 

Regards,
Michael

**Comment by fubar-coder** [comment]
You can get/set the content type by getting/setting the dead property `getcontenttype`.

**Comment by ViceIce** [comment]
Just for reference:

The `PropFindHandler` handler is filtering all dead properties with a cost higher than `0`.
The `TextFile` and `SQLite` `PropertyStores` have a default cost of `10`, so all props are filtered.

For now i use `TextFilePropertyStoreOptions` to set the cost to `0`.

**Comment by fubar-coder** [comment]
The reason behind this is, that the WebDAV server is allowed to return only cheap dead properties when no property was queried explicitly.
