### ISSUE TITLE
Wrong format for creationdate property

### ISSUE THREAD

**Issue by ViceIce** [FubarDevelopment/WebDavServer#27]
The [`creationdate`](https://tools.ietf.org/html/rfc4918#section-15.1) property should use the format defined in [rfc3339#section-5.6](https://tools.ietf.org/html/rfc3339#section-5.6).

Only the [ `getlastmodified`](https://tools.ietf.org/html/rfc4918#section-15.7) property should use the format defined in [rfc2616#section-3.3.1](https://tools.ietf.org/html/rfc2616#section-3.3.1).

**Comment by ViceIce** [comment]
Thanks. 👍

**Comment by MosheL** [comment]
I still have this problem, Windows Hebrew, last version from trunk


this was help on your Sample project:

```` C#
var en = new System.Globalization.CultureInfo("en-GB");
var rc = new RequestCulture(culture: en, uiCulture: en);
var ls = new List<System.Globalization.CultureInfo>() { en };
app.UseRequestLocalization(new RequestLocalizationOptions() { 			 
DefaultRequestCulture = rc, SupportedCultures = ls, SupportedUICultures = ls });

**Comment by fubar-coder** [comment]
@MosheL Can you provide a unit test - or at least tell me what is the current and the expected value?

**Comment by MosheL** [comment]
unit test:

 your sample project  as-is with windows configured with Hebrew Canlendar:

![image](https://user-images.githubusercontent.com/2265043/57930593-0e914980-78bf-11e9-9bc5-499d14d1f36a.png)

the wrong result:

```` XML
<?xml version="1.0" encoding="utf-8"?><D:multistatus xmlns:D="DAV:"><D:response><D:href>/</D:href><D:propstat><D:prop><D:resourcetype><D:collection /></D:resourcetype><D:getlastmodified>Wed, 01 May 2019 09:32:53 GMT</D:getlastmodified>

<D:creationdate>תשע"ט-ח'-כ"וT09:32:53.797+03:00</D:creationdate>

<D:getetag>"ac4a217d-f390-41dc-a9a1-d89d9cf69a04"</D:getetag><D:getcontentlength>0</D:getcontentlength><D:lockdiscovery /><D:supportedlock><D:lockentry><D:lockscope><D:shared /></D:lockscope><D:locktype><D:write /></D:locktype></D:lockentry><D:lockentry><D:lockscope><D:exclusive /></D:lockscope><D:locktype><D:write /></D:locktype></D:lockentry></D:supportedlock></D:prop><D:status>HTTP/1.1 200 OK</D:status></D:propstat></D:response></D:multistatus>

**Comment by MosheL** [comment]
just to note somewhere: I was forced to change the Hosting() function to make Windows Explorer use `Fiddler`  so I could debug things.

Windows internal Proxy mechanism ignore `127.0.0.1` or `localhost` so I could not inspect these requests unil I was changed this:

 private static IWebHostBuilder ConfigureHosting(IWebHostBuilder builder, IConfiguration configuration)
        {
            var forceKestrelUse = configuration.GetValue<bool>("use-kestrel");
            if (!forceKestrelUse && IsWindows)
            {
                builder = builder
                    .UseHttpSys(
                        opt =>
                        {
                            opt.Authentication.Schemes = AuthenticationSchemes.None ;
                            opt.Authentication.AllowAnonymous = true;
							opt.UrlPrefixes.Add("http://*:5000");
						});
            }
            else
            {
                IsKestrel = true;
            }

            return builder;
        }

**Comment by fubar-coder** [comment]
Ok, thank you for the information. I probably know the problem.
