### ISSUE TITLE
what is it different with nwebdav?

### ISSUE THREAD

**Issue by pizixie** [FubarDevelopment/WebDavServer#28]
what is it different with [nwebdav](https://github.com/ramondeklein/nwebdav)?

**Comment by fubar-coder** [comment]
The biggest difference is that it uses asp.net core under the hood and therefore integrates nicely with an existing asp.net core project, benefits from all features and performance improvements, is configurable and extensible using dependency injection and supports virtual file systems.

**Comment by pizixie** [comment]
ehh...
nwebdav also can use asp.net core,and it can run on httplistener and old(classic) asp.net too.

**Comment by fubar-coder** [comment]
The difference is, that this project implemented WebDAV support using a controller. The classic ASP.NET framework was of no interest for me, because it's a legacy platform that's not under active development. The HTTP Listener implementation was not considered, because I had no interest implementing the HTTP protocol.

**Comment by fubar-coder** [comment]
Some other points:

- Documentation
- Lots of unit tests
- Multiple dead property store implementations (in-memory, sqlite, text file)
- Multiple virtual file systems (in-memory, System.IO based file system, sqlite)
- Multiple locking implementations (in-memory, sqlite)
- Recursive locks
- Cross-server MOVE/COPY support
- Tested on Linux (even with PAM authentication)
- Support for `xml:lang`

**Comment by pizixie** [comment]
yes, you are right.
i have some problems when i using basic auth with nwebdav.
i will deep into your project.
