### ISSUE TITLE
Has the myget repository been moved?

### ISSUE THREAD

**Issue by MeliSantana** [FubarDevelopment/WebDavServer#29]
Good afternoon,

We recently notice that when we try to open and build a solution that includes the fubar packages in a machine that doesn't have the packages in cache, it doesn't build and can't find the packages in the configured package source  https://www.myget.org/F/webdav-server/api/v3/index.json. Looks like is not there anymore?
Thank you in advance

**Comment by fubar-coder** [comment]
That is correct. I'm currently in the process of publishing the latest version on NuGet.org

**Comment by fubar-coder** [comment]
The packages are now published on NuGet.org as version 1.0.0

**Comment by MeliSantana** [comment]
Thank you very much for the update.
Regards
