### ISSUE TITLE
Cannot consume IWebDavContext from IRemoteMoveTargetActionsFactory

### ISSUE THREAD

**Issue by MarcusWichelmann** [FubarDevelopment/WebDavServer#34]
As soon as I start a copy or move action I get following error message:
`Cannot consume scoped service 'FubarDev.WebDavServer.IWebDavContext' from singleton 'FubarDev.WebDavServer.Engines.Remote.IRemoteMoveTargetActionsFactory'`.

This seems to happen because the `AddWebDav()` extension adds `IRemoteMoveTargetActionsFactory` as singleton and `IWebDavContext` as scoped service:https://github.com/FubarDevelopment/WebDavServer/blob/c1ffd4e2b16b385351537d26f3b6f6c08412c3e3/src/FubarDev.WebDavServer.AspNetCore/WebDavServicesExtensions.cs#L63
And the `DefaultRemoteTargetActionsFactory ` consumes the webdav context:https://github.com/FubarDevelopment/WebDavServer/blob/3389660d53ed37b21fe350c7b185bdd67b6094fd/src/FubarDev.WebDavServer/Engines/Remote/DefaultRemoteTargetActionsFactory.cs#L32
That looks contradictory to me.

Im registering my services as follows:
```C#
services.AddSingleton(Configuration);
services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
services.AddScoped<IPropertyStoreFactory, RedisPropertyStoreFactory>();
services.AddScoped<IFileSystemFactory, VirtualFileSystemFactory>();
services.AddWebDav();
services.AddCors();
services.AddAuthentication(...);
services.AddMvcCore().[...].AddWebDav();
```

Have I missed something?

**Comment by fubar-coder** [comment]
That is indeed a bug. I'll look into it.

**Comment by fubar-coder** [comment]
The unit tests were wrong. I changed them to uncover this bug and have a patch ready. I'll release an update soon.

**Comment by MarcusWichelmann** [comment]
Wow, that was fast! 😄 
Could you update the NuGet package please, too?

**Comment by fubar-coder** [comment]
They're published, but it may take some time until they're indexed by nuget.org.
