### ISSUE TITLE
Returning custom live properties

### ISSUE THREAD

**Issue by MarcusWichelmann** [FubarDevelopment/WebDavServer#36]
Hi,

is it possible to return custom live properties to the webdav-client to add additional information to the webdav entry?

After looking in the code, I couldn't find an easy way to do this, but maybe I've missed something.

Kind regards, and thank you for making this awesome library! :smile: 
Marcus

**Comment by MarcusWichelmann** [comment]
In case it's not possible I'd be happy to do a pull request.
Just tell me if and how you would like something like that to be implemented.

**Comment by fubar-coder** [comment]
I just looked through the code and the place where the properties are collected is in `IWebDavClass.GetProperties`.

The easiest way to implement you own live collections would be to develop a custom `IWebDavClass` implementation and your own `IWebDavDispatcher`. Its default implementation is the `WebDavServer` class. Create something like:

```csharp
class MyWebDavServer : IWebDavDispatcher {
    /// <summary>
    /// Initializes a new instance of the <see cref="WebDavServer"/> class.
    /// </summary>
    /// <param name="webDavClass1">The WebDAV class 1 implementation</param>
    /// <param name="formatter">The formatter for the WebDAV XML responses</param>
    /// <param name="webDavClass2">The WebDAV class 2 implementation</param>
    public WebDavServer([NotNull] IWebDavOutputFormatter formatter, [NotNull, ItemNotNull] IEnumerable<IWebDavClass2> webDavClasses)
    {
        Formatter = formatter;
        var classes = webDavClasses.ToList();
        Class1 = classes.OfType<IWebDavClass1>().Last();
        Class2 = classes.OfType<IWebDavClass2>().LastOrDefault();
        SupportedClasses = classes;
    }

    /// <inheritdoc />
    public IReadOnlyCollection<IWebDavClass> SupportedClasses { get; }

    /// <inheritdoc />
    public IWebDavOutputFormatter Formatter { get; }

    /// <inheritdoc />
    public IWebDavClass1 Class1 { get; }

    /// <inheritdoc />
    public IWebDavClass2 Class2 { get; }
}
```

Now register your own `IWebDavClass` and `IWebDavDispatcher` implementations and you should be ready to go as long as the cost of your custom properties is 0.

**Comment by MarcusWichelmann** [comment]
Thanks a lot for your support, it works!
Now I do understand how this compilance-class architecture is engineered.

I had to replace the registered `IWebDavDispatcher` implementation because it's registered as `AddScoped` instead of `TryAddScoped`:
https://github.com/FubarDevelopment/WebDavServer/blob/2faf70dd0983cd2f776f270e2c81aacecee2a657/src/FubarDev.WebDavServer.AspNetCore/WebDavServicesExtensions.cs#L74
So my initialization looks like that now (not very clean, but works fine):
```C#
services.AddWebDav();
services.Remove(services.FirstOrDefault(descriptor => descriptor.ServiceType == typeof(IWebDavDispatcher)));
services.AddScoped<IWebDavDispatcher, WebDavServer>();
```
Just wondering: Is there a reason why you're not using `TryAddScoped` here?

**Comment by fubar-coder** [comment]
Are you sure that the `Remove` is required? It should usually take the last registered `IWebDavDispatcher` service when only one is requested. Other than that, I just simply didn't think that someone would need to implement its own dispatcher 😅 .

**Comment by MarcusWichelmann** [comment]
Ah, good to know that the last one will be taken in this case.

It was registered bevore `AddWebDav` until I tried the `Remove` way. Then this will work probably, too. But I think I'll leave it like this because removing the service explicitly makes it more clear what's happening here.

> I just simply didn't think that someone would need to implement its own dispatcher sweat_smile .

Murphys law :stuck_out_tongue:

**Comment by MarcusWichelmann** [comment]
Note for others trying to do the same thing:
Thanks to this change, this should be way easier and cleaner to do now:
https://github.com/FubarDevelopment/WebDavServer/commit/35a0f16ce19d570996204e3b93b01a87179c8df4
