### ISSUE TITLE
Where can I find the source code for version 1.0.1?

### ISSUE THREAD

**Issue by rliberoff** [FubarDevelopment/WebDavServer#37]
Hi!

Awesome library!!!

I'm currently referencing your NuGet package for version 1.0.1, and wanted to see something on the code, but I'm unable to find a branch or tag for said version.

Where can I find it?

Thank you in advance.

Regards,

Rodrigo

**Comment by fubar-coder** [comment]
Yeah, I forgot to tag this release. I added a tag `v1.0.1` which happens to be `master`, because all development happens in `release/2.0`..

**Comment by rliberoff** [comment]
Perfect!

Thank you.
