### ISSUE TITLE
Broken path handling with special characters

### ISSUE THREAD

**Issue by MarcusWichelmann** [FubarDevelopment/WebDavServer#39]
Hi, it's me again.

While dealing with LibreOffice locking files which are named like `.~lock.am Schlussodt#` I noticed that renaming such a file through WebDAV fails.
After a lot of debugging I discovered, that WebDavContext.ControllerRelativeUrl contains the full URL to the locking-file instead of just the controller URL. And, as you can probably imagine, this has many strange side-effects.

See following screenshots for further explaination of why this happens:

**Expected behaviour** while renaming `heile.txt`:
![image](https://user-images.githubusercontent.com/5501487/54076763-42446780-42af-11e9-8d4a-2335afc1b6dc.png)

**Broken behaviour** while renaming `.~lock.am Schlussodt#`:
![image (1)](https://user-images.githubusercontent.com/5501487/54076780-76b82380-42af-11e9-9aab-1e36505096ba.png)
As you can see, the ending of `path` and `input` is different due to the escaping of the `#` character which results in the `remaining` variable containing the full path to the file.

Code:
https://github.com/FubarDevelopment/WebDavServer/blob/2faf70dd0983cd2f776f270e2c81aacecee2a657/src/FubarDev.WebDavServer.AspNetCore/WebDavContext.cs#L86

Do you habe an idea how to fix this behaviour?

King regards,
Marcus

**Comment by fubar-coder** [comment]
The fix seems (at first) simple: Just change the line to:

```csharp
var pattern = string.Format("{0}$", Regex.Escape(path.UriEscape())); 
```

I really hope that the new routing in ASP.NET Core 3.0 returns the same values.

**Comment by MarcusWichelmann** [comment]
Great!
Ah, and you're working on a 2.0 release? Awesome. Is there a roadmap and when are you planning to release it?

**Comment by fubar-coder** [comment]
Regarding the v2.0 release. I'm uncertain when it comes out. There are some breaking changes, but nothing *really* major yet.

**Comment by retroplasma** [comment]
I stumbled upon a similar issue but in read-only mode. There are some paths on the OS that don't resolve in WebDav. I created a hierarchy like this: `/a/    %20 . %x#,%2F %2F     /b/c/d` and mounted it using the sample project, but it stops traversing before `b`:

|OS hierarchy|Mounted hierarchy|
|------------|-------------|
|<img src="https://user-images.githubusercontent.com/46618410/61759110-a895d680-adc7-11e9-8e34-ba1b723ee0cd.png">|<img src="https://user-images.githubusercontent.com/46618410/61759125-b77c8900-adc7-11e9-881e-1a8ff0e2b6e5.png">|



Other example: paths like `a %b/a` are resolved but lead to this:

|OS hierarchy|Mounted hierarchy|
|------------|-------------|
|<img src="https://user-images.githubusercontent.com/46618410/61758863-b5fe9100-adc6-11e9-8e38-133822c4c2ca.png">|<img src="https://user-images.githubusercontent.com/46618410/61758871-beef6280-adc6-11e9-9a53-38ca7e11b8b3.png">|

In a previous ASP.NET project I used this function below for escaping the whole path, but couldn't integrate it into the WebDav project yet. I was a bit confused by the Uri class in general, so I used strings. Maybe it helps?
```csharp
string escape(string wholePath)
{
	Func<string, string> esc = x =>
	{
		// handle leading and trailing spaces
		var s = System.Uri.EscapeDataString($"a{x}a");
		return s.Substring(0, s.Length - 1).Substring(1);
	};

	var split = wholePath.Split('/').Select(esc).ToArray();
	return split.Aggregate("", (a, b) => a + "/" + b).Substring(1);
}
```
