### ISSUE TITLE
Limit WebDavExceptionFilter to WebDavControllerBase

### ISSUE THREAD

**Issue by MarcusWichelmann** [FubarDevelopment/WebDavServer#40]
Is it possible to to register the `WebDavExceptionFilter` only for the MVC actions inside the `ẀebDavControllerBase`?
In my case, the WebDav server is only a small part of a big application and it's a little bit annoying, that any exception thrown in other MVC actions is also handled by this exception filter and logged multiple times.

Maybe an `ExceptionFilterAttribute` would be a good replacement?

**Comment by fubar-coder** [comment]
Fixed in the release/2.0 branch
