### ISSUE TITLE
Read-only mode when using ms-word:ofe|u|

### ISSUE THREAD

**Issue by Goulpe** [FubarDevelopment/WebDavServer#41]
Hello !

I have an issue when I open a Word file via `Chrome` using the command `ms-word:ofe|u|http://localhost:5000/Test.docx`. The document open in read-only mode.
Log returns me a `HTTP status code 304`

If I open the document using the `file explorer`, the LOCK file is present and the main Word is in read-write mode.

In attach, you will find logs using `Chrome` and `file explorer`.

Best regards,
Goulpe

[Chrome.txt](https://github.com/FubarDevelopment/WebDavServer/files/3130660/Chrome.txt)
[File explorer.txt](https://github.com/FubarDevelopment/WebDavServer/files/3130661/File.explorer.txt)

**Comment by fubar-coder** [comment]
It seems that chome sends either a `If-None-Match` or a `If-Modified-Since` header. Can you please check which header was sent?

**Comment by Goulpe** [comment]
If it's the first time I open the Word, I only get `HTTP status code 200` : 
<img width="836" alt="Capture" src="https://user-images.githubusercontent.com/25847582/56966036-a8869180-6b5e-11e9-9e13-870df4c24c86.PNG">

If it's a second time, I get a `HTTP status code 304` : 
<img width="834" alt="Capture2" src="https://user-images.githubusercontent.com/25847582/56966125-d2d84f00-6b5e-11e9-83b1-f5c0172d3fe0.PNG">

Using `ms-word:ofe|u|http://localhost.fiddler:5000/Test.docx` command with Fiddler.

In both cases, I get a read-only document.

Thanks !

**Comment by fubar-coder** [comment]
OK, so he opens it and checks if there were changes. You get a 304, because there are no changes since the last GET request, which seems to be correct.

Which version of the library do you use? Maybe you can try the version on [MyGet.org](https://www.myget.org/gallery/webdav-server)?

The nuget V3 feed URL is: https://www.myget.org/F/webdav-server/api/v3/index.json.

**Comment by Goulpe** [comment]
Here is somes informations : 
- Target framework : .NET Core 2.1
- NuGets package : 
<img width="480" alt="Capture" src="https://user-images.githubusercontent.com/25847582/56970307-264e9b00-6b67-11e9-97b7-740bb0533483.PNG">

I try with the lastet version on MyGet and I keep you updated !

Thanks

**Comment by Goulpe** [comment]
I tried with the lastet version of `WebDavServer` but I still have the read-only mode :

Packages : 
<img width="629" alt="Capture" src="https://user-images.githubusercontent.com/25847582/56985171-024f8180-6b88-11e9-8790-7cf161345ba4.PNG">

Fiddler : 
![Uploading Capture2.PNG…]()

Have you an idea ?

Thanks for helping !

**Comment by fubar-coder** [comment]
Thank you for your information. I don't have an idea yet, but I'll look into it.

**Comment by fubar-coder** [comment]
Maybe this is related: https://social.technet.microsoft.com/Forums/en-US/06fedd90-4889-45ca-949d-60b76d74dd15/ms-word-open-document-readonly-with-webdav

Please test if the solution there works for you too.

**Comment by fubar-coder** [comment]
It's most likely a missing header (thanks to Mr. Graulich who found the reason for this behavior). It **should** be sufficient to add the header `MS-Author-Via: DAV` to the response of the `OPTIONS` request.

**Comment by Goulpe** [comment]
I'm not sure how to add the header. In the `WebDavController`, `context.RequestHeaders.Headers` use an `IReadOnlyDictionary` which do not allow me to add a header.

Can you give me an other method ?

Thanks !

**Comment by fubar-coder** [comment]
The current workaround (until the next preview release) is:

1. Make your own copy of [OptionsHandler.cs](https://github.com/FubarDevelopment/WebDavServer/blob/release/2.0/src/FubarDev.WebDavServer/Handlers/Impl/OptionsHandler.cs)
2. Register it with `services.AddTransient<IClass1Handler, YourOptionsHandlerCopy>()` **after** adding the WebDAV services with `services.AddWebDav()`

**Comment by Goulpe** [comment]
I applied the workaround and it works !!

Thank you for the support and for the library.

Cheers !
