### ISSUE TITLE
Overriding handlers

### ISSUE THREAD

**Issue by guntarspaluhs** [FubarDevelopment/WebDavServer#44]
Hi!

I've tried to override GetHeadHandler and register it in Startup.cs after .AddWebDav(), but my GetHeadHandler isn't calling in debug mode.

Could you give an example, how to override your handlers?

**Comment by fubar-coder** [comment]
You have two options:

- Manual registration
- [`Scrutor`](https://www.nuget.org/packages/Scrutor/)

# Manual registration

```csharp
services.AddTransient<IClass1Handler, YourCustomGetHeadHandler>();
```

You still need to implement `IGetHandler` and7or `IHeadHandler`.

# [`Scrutor`](https://www.nuget.org/packages/Scrutor/)

Example:

```csharp
services.Scan(
	scan => scan
		.FromAssemblyOf<YourCustomGetHeadHandler>()
		.AddClasses(classes => classes.AssignableToAny(typeof(IHandler)))
		.AsImplementedInterfaces()
		.WithTransientLifetime());
```
