### ISSUE TITLE
Abort reading from stream when request has been aborted

### ISSUE THREAD

**Issue by retroplasma** [FubarDevelopment/WebDavServer#47]
Hi,

First of all, thanks for the wonderful project! There is a thing that I couldn't figure out yet:

I implemented an `IFileSystem`, `IDocument` and so forth. When `GET`ting large files I noticed that if the request is aborted by the client, the server keeps reading data using `OpenReadAsync` from my subclass of `Stream` (the read method keeps being called). The `cancellationToken` doesn't seem to be triggered. Can we access `HttpContext.RequestAborted` somehow? Or is there another preferred way to react to client-side cancellation of a request?

I tested it by `cURL`ing the server (`curl http://localhost:5809/_dav/file.dat`) and aborting using CTRL+C.

Thanks!

**Comment by fubar-coder** [comment]
That's a tough question. I'd check if this is a problem with the stream or if the cancellation token isn't triggered

**Comment by retroplasma** [comment]
@fubar-coder I put logs in the Stream's `ReadAsync` and `Read` function and checked the cancellation token from `ReadAsync` as well as the one from `OpenReadAsync`. The tokens are not triggered when the request is cancelled by the client.

Maybe this line is the cause?https://github.com/FubarDevelopment/WebDavServer/blob/master/src/FubarDev.WebDavServer/Handlers/Impl/GetResults/WebDavFullDocumentResult.cs#L73
(`await content.CopyToAsync(response.Body).ConfigureAwait(false);`)

**Comment by fubar-coder** [comment]
Good catch! I will fix this.

**Comment by retroplasma** [comment]
@fubar-coder i ran the new code; unfortunately cancellation is still not triggered for me if the client cancels the request.

**Comment by fubar-coder** [comment]
Hmm, ok, will try again. I'm currently fighting the build server 😢

**Comment by retroplasma** [comment]
Thanks for doing this! I'm looking around as well and just found [this IIS issue](https://github.com/aspnet/AspNetCoreModule/issues/38), but I'm only using Kestrel and they fixed something like this [here](https://github.com/aspnet/KestrelHttpServer/issues/1139). I'm new to ASP though and not 100% sure if that's related.

**Comment by retroplasma** [comment]
@fubar-coder It works if I give `WebDavIndirectResult` a cancellation token ([here](https://github.com/FubarDevelopment/WebDavServer/blob/master/src/FubarDev.WebDavServer.AspNetCore/WebDavIndirectResult.cs#L80))

After that I want to check`WebDavPartialDocumentResult` because partial DLs are not cancelled
