### ISSUE TITLE
"FubarDev.WebDavServer.XmlSerializers.dll" Does not exist

### ISSUE THREAD

**Issue by KAW0** [FubarDevelopment/WebDavServer#49]
`System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly '#Project#\bin\Debug\netcoreapp2.2\FubarDev.WebDavServer.XmlSerializers.dll'. The specified file could not be found.
  Source=<The source of the exception cannot be evaluated>
  Stack Trace:
<Unable to evaluate tracking data>
`

**Comment by fubar-coder** [comment]
This is expected, see: [XmlSerializer giving FileNotFoundException at constructor](https://stackoverflow.com/q/1127431).
