### ISSUE TITLE
Path handling broken with ASP.Net Core 3.0

### ISSUE THREAD

**Issue by MarcusWichelmann** [FubarDevelopment/WebDavServer#53]
As you have foreseen, the behaviour of your path logic is different with ASP.Net Core 3.0: https://github.com/FubarDevelopment/WebDavServer/commit/19f45044afe893f74d6f33b92a307270095bf558
This completely breaks the directory tree now.

Debugger:
![image](https://user-images.githubusercontent.com/5501487/67315607-37210d80-f507-11e9-9c6d-af8c99297bf7.png)

https://github.com/FubarDevelopment/WebDavServer/blob/release/2.0/src/FubarDev.WebDavServer.AspNetCore/WebDavContext.cs#L87

**Comment by fubar-coder** [comment]
Issue should be fixed now. The fix is in `2.0.0-beta.81` in the public Azure DevOps feed:

https://pkgs.dev.azure.com/fubar-development/webdav-server/_packaging/webdav-server/nuget/v3/index.json
