### ISSUE TITLE
Don't allow clients to see contents of a collection?

### ISSUE THREAD

**Issue by jessebarocio** [FubarDevelopment/WebDavServer#58]
Is it possible to configure the server in such a way that a client must have a direct URL to access a file? I don't want them to be able to see or discover the contents of a collection.

**Comment by fubar-coder** [comment]
Maybe you can try to implement a request filter that forbids `PROPFIND` on a collection?

**Comment by andreasringdal** [comment]
You can create your own file system and control what is visible at every level.
We used this to emulate folders using customer names, and adding subfolders for each project.
https://github.com/FubarDevelopment/WebDavServer/blob/a11219eece75c5daa6dc2f7126fc705765a29920/articles/custom-fs.md
