### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by albertoarmida** [FubarDevelopment/WebDavServer#59]
I am using version 2.0 and, despite the use of user tester, trying to connect through Windows Explorer continues to display the username and password input form. The user's homedir is present, as is the temporary folder "webdav" in the temp of the user with whom the service is running.

**Comment by fubar-coder** [comment]
This indicates a problem with HTTP Basic authentication.

Follow the instruction in the following question:

https://stackoverflow.com/questions/13413914/how-to-enable-basic-authentication-for-webdav-on-windows-8

A reboot might be necessary before it'll work.
