### ISSUE TITLE
How to support digest authentication

### ISSUE THREAD

**Issue by bonnlee2016** [FubarDevelopment/WebDavServer#62]
Hi:  fubar dev
      I refer to some websites about webDavServer.   Basic  Authentication is that sends passwords over the connection in clear text.  So how to support digest authenticaition.   could you gave me some help.

Thank U.

**Comment by fubar-coder** [comment]
It uses the same authentication/authorization mechanisms from ASP.NET Core. Just enable digest authentication for ASP.NET Core and you've enabled it for WebDAV too.
