### ISSUE TITLE
Cannot run the test server

### ISSUE THREAD

**Issue by michalsteyn** [FubarDevelopment/WebDavServer#64]
This issue is related to the closed issue of: #48

I have made the recommended regedit changes mentioned in the linked issue.
And I also tried to use the http://localhost:5809/_dav/.

When trying to this as a Network Location in Explorer or trying to add as a Mapped Drive, it always fails. 
Explorer complains that it is not a valid endpoint. 

I can see in VS Debug, that the endpoint is being accessed, and that it responds with an unauthorized code. But Explorer never shows the login dialog.

Any other recommendations or documentation would be highly appreciated.

**Comment by fubar-coder** [comment]
I'll take a look at this issue next week, when I'm back from vacation.

**Comment by fubar-coder** [comment]
Can you tell me more about your system and what you've tried? To be precise:

- Which OS (and OS version) are you using?
- What is your WebDAV client?
- The sample application uses HTTP BASIC authentication over non-SSL connection
  - Did you enable this in Windows? (https://www.windowspage.de/tipps/022703.html)
  - Did you authenticate as the test user: `tester`, password `noGh2eefabohgohc`?

**Comment by maulik-modi** [comment]
@michalsteyn , did you manage to resolve the issue?

**Comment by fubar-coder** [comment]
The latest version from the release/2.0 branch should work. It was tested against the following clients:

- cadaver
- ng
- Windows 10
- Gnome Nautilus
